name: WASM

on:
  push:
    branches: [main, 78-add-base-jekyll-site-for-wasm]
  pull_request:
    branches: [main]

jobs:
  wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Install Jekyll & dependencies
        run: |
          sudo apt-get install -y ruby-full build-essential zlib1g-dev
          sudo gem install bundler
          cd ./website/jekyll_site
          bundle install
          cd ../../
    
      - name: Compile WASM & Website
        run:  python3 -m website.compile_site

      # TODO: Update Github pages to reflect new WASM