name: WASM

on:
  push:
    branches: [main, 78-add-base-jekyll-site-for-wasm]
  pull_request:
    branches: [main]

jobs:
  wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest
    
      - name: Compile WASM
        run:  python3 -m website.compile_site

      - name: Switch To Jekyll Dir
        run: cd ./website/jekyll_site
      
      - name: Compile Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./website/jekyll_site
          destination: ./website/jekyll_site/_site

      # TODO: Update Github pages to reflect new WASM